### PR TITLE
Support update to FreshRSS 1.24.0

### PR DESCRIPTION
**Pull request by math-GH**
1.24.0 is ready for delivering

### CODE REVIEW

**Review by Alkarex — APPROVED** [review]

**Comment by beerisgood** [comment]
Does it need some time? No updates available for me:
image

**Comment by math-GH** [comment]
Waiting for @marienfressinaud who will update update.freshrss.org

It is a step-by-step release process.

**Comment by Alkarex** [comment]
It is one of the many things https://github.com/FreshRSS/FreshRSS/pull/1760 should address, but it is waiting for a caring hand :-P

**Comment by marienfressinaud** [comment]
It should work now!

**Comment by beerisgood** [comment]
Update was successful 🍺

**Pull request merged**
