### PR TITLE
Support update to FreshRSS 1.24.3

### PR DESCRIPTION
**Pull request by math-GH**

### CODE REVIEW

**Comment by Alkarex** [comment]
Ping @marienfressinaud 
Damn, I forgot that I should not merge here :-P

**Comment by math-GH** [comment]
For the documentation for the silent readers: The update code needs to be uploaded to our servers yet. After that last step 1.25.0 will be available via the webupdater too

**Comment by math-GH** [comment]
@Alkarex thanks for the corrected headline that I made by copy&paste :D

**Comment by marienfressinaud** [comment]
For the documentation for the silent readers: our server is updated :grinning:

**Comment by Alkarex** [comment]
🎄

**Comment by beerisgood** [comment]
Update over web interface was successfully here 🍺

**Pull request merged**
